name: Docker push
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

#      - name: Install versionize
#        run: dotnet tool install --global Versionize
#
#      - name: Bump versions
#        run: versionize
#
#      - name: Create tags
#        run : git push --follow-tags origin main

      - uses: actions/checkout@v2.5.0
      - name: Set Release Version
        run: |
          echo "BUILD_VERSION=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      - name: Extract version
        run: export DARKSUN_VERSION=$(xmllint --shell DarkStar.Engine/DarkStar.Engine.csproj  <<< "cat //Version/text()" | grep -v "^/ >" | tail -n 1)
      - name: View version
        run: echo $DARKSUN_VERSION
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: tgiachi/darkstar.server:latest